// import { Inter } from "next/font/google";
import { Kanit } from "next/font/google";

import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css';

// const inter = Inter({ subsets: ["latin"] });

const kanit = Kanit({
  subsets: ['thai', 'latin'],
  weight: ['300', '400', '600', '700'],
  variable: '--font-kanit',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={kanit.variable}>
      <body>
        {children}
      </body>
    </html>
  );
}
